FROM craigjperry/fedora20
MAINTAINER Craig J Perry "craigp84@gmail.com"
RUN yum -y install wget && wget --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/7u67-b01/jdk-7u67-linux-x64.rpm && yum -y localinstall jdk-7u67-linux-x64.rpm

